name: myoro_matchup
description: "An application to gather your friends for organized sports."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  myoro_flutter_library: ^2.7.0
  myoro_flutter_annotations: ^1.4.10
  provider: ^6.1.5
  get_it: ^8.0.3
  injectable: ^2.5.0
  faker: 2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^16.0.0
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  http: ^1.1.0
  shared_preferences: ^2.5.3
  email_validator: ^3.0.0
  sentry_flutter: ^9.8.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/cats/
    - assets/images/png/
    - assets/images/svg/
